<img src='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-VfNtOyJbsaxu43Kztf_cv1mgBG6ZIQZEVw&usqp=CAU'>

# Procesamiento de Lenguage Natural

## Taller #5: TF-IDF
`Fecha de entrega: Septiembre 19, 2020. (Antes del inicio de la próxima clase).`

`Modo de entrega: Subir link de GitHub al aula virtual.`

In [2]:
import re
import numpy as np
import pandas as pd

from nltk.corpus import stopwords
stopwords_sp = stopwords.words('spanish')

from nltk.stem.snowball import SnowballStemmer
spanishStemmer=SnowballStemmer("spanish")

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Punto 1: Pre-Procesamiento

- `[18 pts]` Leer el archivo `Princesas.csv` usando `pandas` y crear una nueva columna con el texto en minúscula, sin caracteres especiales ni números, sin palabras vacias y hacer stemming de las palabras

In [4]:
princesas=pd.read_csv(r'D:\NLP\Clase5-12-09-20\Princesas.csv', sep=',')
princesas

       Princesa                                       Personalidad
0  Blancanieves  Blancanieves es una princesa de noble cuna que...
1    Cenicienta  Cenicienta es inicialmente una sirvienta en su...
2        Aurora  La Princesa Aurora, la Bella Durmiente, es la ...
3         Bella  Bella es una muchacha que vive en la campiña f...
4        Jasmín  Cuando se introdujo por primera vez, la Prince...
5    Pocahontas  El nombre de Pocahontas significa "Pequeña Sil...
6         Mulan  Mulan es atípica a los anteriores papeles feme...
7         Tiana  Es una joven camarera que sueña con ser dueña ...
8        Mérida  Mérida llama la atención por su característico...
9         Moana  Moana, una joven de 16 años de edad, hija únic...

In [6]:
#crear nueva columna y convertir a minúsculas 
princesas['pre-procesado'] = princesas['Personalidad'].str.lower() # Minúscula
princesas

,Princesa,Personalidad,pre-procesado
0,Blancanieves,Blancanieves es una princesa de noble cuna que...,blancanieves es una princesa de noble cuna que...
1,Cenicienta,Cenicienta es inicialmente una sirvienta en su...,cenicienta es inicialmente una sirvienta en su...
2,Aurora,"La Princesa Aurora, la Bella Durmiente, es la ...","la princesa aurora, la bella durmiente, es la ..."
3,Bella,Bella es una muchacha que vive en la campiña f...,bella es una muchacha que vive en la campiña f...
4,Jasmín,"Cuando se introdujo por primera vez, la Prince...","cuando se introdujo por primera vez, la prince..."
5,Pocahontas,"El nombre de Pocahontas significa ""Pequeña Sil...","el nombre de pocahontas significa ""pequeña sil..."
6,Mulan,Mulan es atípica a los anteriores papeles feme...,mulan es atípica a los anteriores papeles feme...
7,Tiana,Es una joven camarera que sueña con ser dueña ...,es una joven camarera que sueña con ser dueña ...
8,Mérida,Mérida llama la atención por su característico...,mérida llama la atención por su característico...
9,Moana,"Moana, una joven de 16 años de edad, hija únic...","moana, una joven de 16 años de edad, hija únic..."

In [8]:
# data procesada
princesas['pre-procesado']= princesas['pre-procesado'].apply(lambda x: re.sub(r"[\W\d_]+", " ", str(x)))
princesas['pre-procesado'] = princesas['pre-procesado'].apply(lambda x: ' '.join([palabra for palabra in x.split() if palabra not in (stopwords_sp)]))
princesas

,Princesa,Personalidad,pre-procesado
0,Blancanieves,Blancanieves es una princesa de noble cuna que...,blancanieves princesa noble cuna ve forzada se...
1,Cenicienta,Cenicienta es inicialmente una sirvienta en su...,cenicienta inicialmente sirvienta casa constan...
2,Aurora,"La Princesa Aurora, la Bella Durmiente, es la ...",princesa aurora bella durmiente hija única rei...
3,Bella,Bella es una muchacha que vive en la campiña f...,bella muchacha vive campiña francesa padre inv...
4,Jasmín,"Cuando se introdujo por primera vez, la Prince...",introdujo primera vez princesa jasmín pocos dí...
5,Pocahontas,"El nombre de Pocahontas significa ""Pequeña Sil...",nombre pocahontas significa pequeña silenciosa...
6,Mulan,Mulan es atípica a los anteriores papeles feme...,mulan atípica anteriores papeles femeninos pel...
7,Tiana,Es una joven camarera que sueña con ser dueña ...,joven camarera sueña ser dueña propio restaura...
8,Mérida,Mérida llama la atención por su característico...,mérida llama atención característico pelo anar...
9,Moana,"Moana, una joven de 16 años de edad, hija únic...",moana joven años edad hija única sucesora impo...

# Punto 2: TF-IDF

- `[16 pts]` Crear la matriz TF-IDF

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

 

tfidf_vect = TfidfVectorizer()
tfidf = tfidf_vect.fit_transform(princesas['pre-procesado'].values)

 

tfidf_matrix = pd.DataFrame(tfidf.toarray(), columns=tfidf_vect.get_feature_names())
tfidf_matrix.index = princesas.index

 

tfidf_matrix = tfidf_matrix.T.round(3)
tfidf_matrix.columns = princesas.Princesa.values #muestra los nombres de las princesas
tfidf_matrix

,Blancanieves,Cenicienta,Aurora,Bella,Jasmín,Pocahontas,Mulan,Tiana,Mérida,Moana
abrumada,0.000,0.0,0.066,0.0,0.0,0.000,0.000,0.000,0.000,0.000
abuela,0.000,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.102
acuerdo,0.000,0.0,0.056,0.0,0.0,0.000,0.000,0.000,0.083,0.000
además,0.000,0.0,0.000,0.0,0.0,0.098,0.000,0.000,0.000,0.000
afortunados,0.087,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...
waka,0.000,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.102
área,0.000,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.098,0.000
época,0.000,0.0,0.000,0.0,0.0,0.000,0.123,0.000,0.000,0.000
ésta,0.000,0.0,0.000,0.0,0.0,0.000,0.000,0.133,0.000,0.000
única,0.000,0.0,0.056,0.0,0.0,0.000,0.000,0.000,0.000,0.087

# Punto 3: Distancia del coseno
- `[12 pts]` Calcular la distancia del coseno entre cada una de las princesas
- `[2 pts]` ¿Cuáles son las princesas más parecidas?
- `[2 pts]` ¿Cuáles son las princesas más diferentes?

In [22]:
from sklearn.metrics.pairwise import cosine_distances

 

dist_cos = cosine_distances(tfidf_matrix.T.values)
dist_cos = pd.DataFrame(dist_cos, columns = tfidf_matrix.columns, index = tfidf_matrix.columns)
dist_cos

,Blancanieves,Cenicienta,Aurora,Bella,Jasmín,Pocahontas,Mulan,Tiana,Mérida,Moana
Blancanieves,0.000000,0.866797,0.894826,0.924564,0.943613,0.938101,0.902638,0.977888,0.989218,0.968750
Cenicienta,0.866797,0.000000,0.923960,0.959074,0.978082,0.973134,0.963874,0.940412,0.993106,0.984062
Aurora,0.894826,0.923960,0.000000,0.879406,0.949429,0.915074,0.922912,0.963668,0.964094,0.972084
Bella,0.924564,0.959074,0.879406,0.000000,0.893927,0.912105,0.898804,0.980095,0.986298,0.943764
Jasmín,0.943613,0.978082,0.949429,0.893927,0.000000,0.944627,0.974709,0.956344,0.968981,0.967041
Pocahontas,0.938101,0.973134,0.915074,0.912105,0.944627,0.000000,0.918213,0.966241,0.979011,0.935330
Mulan,0.902638,0.963874,0.922912,0.898804,0.974709,0.918213,0.000000,0.990616,0.987046,0.956046
Tiana,0.977888,0.940412,0.963668,0.980095,0.956344,0.966241,0.990616,0.000000,0.986056,0.996094
Mérida,0.989218,0.993106,0.964094,0.986298,0.968981,0.979011,0.987046,0.986056,0.000000,0.988911
Moana,0.968750,0.984062,0.972084,0.943764,0.967041,0.935330,0.956046,0.996094,0.988911,0.000000